# basic options
title: Gasifier production
author: Anthony Simm
email: thecarbonshifters@gmail.com
description: A site where you can contribute to our gasifier production videos 
twitter_username: 
github_username:  zorbathegreek
baseurl: Gasifier-Production
 
# Build settings
markdown: kramdown
theme: minima
